[package]
name = "rust-tgirc"
version = "0.1.0"
authors = ["Porter Smith <flowbish@gmail.com>"]

[dependencies]
mime = "^0.1.3, <= 0.1.3"
multipart = "^0.4"
telegram-bot = { path = "../telegram-bot" }
irc = "0.10.1"
