[package]
name = "rust-tgirc"
version = "0.1.0"
authors = ["Porter Smith <flowbish@gmail.com>"]

[dependencies]
mime = "^0.1.3, <= 0.1.3"
multipart = "^0.4"
telegram-bot = { git = "https://github.com/flowbish/telegram-bot.git", rev = "f57fa5e9" }
hyper = "*"
irc = "0.10.1"
